# Basic Yarn 3 configuration
nodeLinker: node-modules
enableImmutableInstalls: false

# Use the bundled yarn version
yarnPath: .yarn/releases/yarn-3.2.3.cjs

# Only keep essential package extension for bigint-buffer
packageExtensions:
  "bigint-buffer@*":
    dependencies:
      node-gyp: "^10.2.0"

# Disable global cache to avoid permission issues
enableGlobalCache: false
